//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerHealthCheck.views.hora
{
    public partial class index
    {
    }
}
