//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerHealthCheck.RegisterControllerService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RegisterControllerService.RegisterControllerSoap")]
    public interface RegisterControllerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/newRegisterInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        CustomerHealthCheck.RegisterControllerService.RegisterInfo newRegisterInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProvince", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Data.DataTable GetProvince();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIndustryType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Data.DataTable GetIndustryType();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTitleName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Data.DataTable GetTitleName(CustomerHealthCheck.RegisterControllerService.PersonType type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetObjTerm", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Data.DataTable GetObjTerm();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetChannel", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Data.DataTable GetChannel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUIDMapRegiterType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        CustomerHealthCheck.RegisterControllerService.UIDMapCustomerProfileModel GetUIDMapRegiterType(string uid, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calculateScore", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        CustomerHealthCheck.RegisterControllerService.ScoreInfo calculateScore(CustomerHealthCheck.RegisterControllerService.RegisterInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calculateDSCR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        CustomerHealthCheck.RegisterControllerService.RegisterInfo calculateDSCR(CustomerHealthCheck.RegisterControllerService.RegisterInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/calculateTCGScoreAndRBP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        CustomerHealthCheck.RegisterControllerService.RegisterInfo calculateTCGScoreAndRBP(CustomerHealthCheck.RegisterControllerService.RegisterInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRegisterInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        int InsertRegisterInfo(CustomerHealthCheck.RegisterControllerService.RegisterInfo info, CustomerHealthCheck.RegisterControllerService.ScoreInfo score);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertCustomerProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        string InsertCustomerProfile(CustomerHealthCheck.RegisterControllerService.RegisterInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertContactProfile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        void InsertContactProfile(CustomerHealthCheck.RegisterControllerService.RegisterInfo info, string customerCode, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        string InsertRequest(string customerCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertFieldData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        void InsertFieldData(CustomerHealthCheck.RegisterControllerService.RegisterInfo info, CustomerHealthCheck.RegisterControllerService.ScoreInfo score);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertUIDRegisterInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        bool InsertUIDRegisterInfo(string uid, int registerInfoId, string infoType, string subInfoType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateRegisterInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        bool UpdateRegisterInfo(CustomerHealthCheck.RegisterControllerService.RegisterInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateConsent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        bool UpdateConsent(CustomerHealthCheck.RegisterControllerService.RegisterInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCodeFromClinic", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        bool UpdateCodeFromClinic(int id, string clinicCustomerCode, string clinicRequestNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        bool UpdateUID(string uid, string customerProfileCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        CustomerHealthCheck.RegisterControllerService.TaskOfResultAPIInfo SendEmail(CustomerHealthCheck.RegisterControllerService.EmailInfo emailInfo);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PersonType personTypeField;
        
        private EstablishmentType officeTypeField;
        
        private int yearIncorporateField;
        
        private string industryCodeField;
        
        private string provinceCodeField;
        
        private string regionCodeField;
        
        private int ownerAgeField;
        
        private MaritalType maritalStatusField;
        
        private int yearExperienceField;
        
        private DebtStatusType debtStatusField;
        
        private int tdrAmountField;
        
        private int tdrYearField;
        
        private double assetValueField;
        
        private double debtValueField;
        
        private double incomeField;
        
        private double expenseField;
        
        private double installmentAmountField;
        
        private IsGetProfit isGetProfitField;
        
        private int objectiveTermField;
        
        private double loanAmountField;
        
        private int yearInstallmentField;
        
        private int idField;
        
        private int consentField;
        
        private string requestNoField;
        
        private int eventTypeField;
        
        private double costSaleField;
        
        private string loanTypeField;
        
        private double dSCRField;
        
        private double loanLCTRField;
        
        private double loanLGField;
        
        private double loanPNField;
        
        private double loanODField;
        
        private double loanTLField;
        
        private double loanOtherField;
        
        private double landAssetField;
        
        private double tCGScoreRBPField;
        
        private int tCGScoreTotalScoreField;
        
        private string tCGScoreBandField;
        
        private int tCGScoreBandLevelField;
        
        private System.Nullable<int> isPassCreditBureauField;
        
        private System.Nullable<int> creditBureauLevelField;
        
        private string titleField;
        
        private string nameField;
        
        private string surnameField;
        
        private string businessNameField;
        
        private string phoneField;
        
        private string idCardField;
        
        private string remarkField;
        
        private string emailField;
        
        private string uidField;
        
        private bool isPassProductCriteriaField;
        
        private double sumAssetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PersonType personType {
            get {
                return this.personTypeField;
            }
            set {
                this.personTypeField = value;
                this.RaisePropertyChanged("personType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EstablishmentType officeType {
            get {
                return this.officeTypeField;
            }
            set {
                this.officeTypeField = value;
                this.RaisePropertyChanged("officeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int yearIncorporate {
            get {
                return this.yearIncorporateField;
            }
            set {
                this.yearIncorporateField = value;
                this.RaisePropertyChanged("yearIncorporate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string industryCode {
            get {
                return this.industryCodeField;
            }
            set {
                this.industryCodeField = value;
                this.RaisePropertyChanged("industryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string provinceCode {
            get {
                return this.provinceCodeField;
            }
            set {
                this.provinceCodeField = value;
                this.RaisePropertyChanged("provinceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string regionCode {
            get {
                return this.regionCodeField;
            }
            set {
                this.regionCodeField = value;
                this.RaisePropertyChanged("regionCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int ownerAge {
            get {
                return this.ownerAgeField;
            }
            set {
                this.ownerAgeField = value;
                this.RaisePropertyChanged("ownerAge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public MaritalType maritalStatus {
            get {
                return this.maritalStatusField;
            }
            set {
                this.maritalStatusField = value;
                this.RaisePropertyChanged("maritalStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int yearExperience {
            get {
                return this.yearExperienceField;
            }
            set {
                this.yearExperienceField = value;
                this.RaisePropertyChanged("yearExperience");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public DebtStatusType debtStatus {
            get {
                return this.debtStatusField;
            }
            set {
                this.debtStatusField = value;
                this.RaisePropertyChanged("debtStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int TdrAmount {
            get {
                return this.tdrAmountField;
            }
            set {
                this.tdrAmountField = value;
                this.RaisePropertyChanged("TdrAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int TdrYear {
            get {
                return this.tdrYearField;
            }
            set {
                this.tdrYearField = value;
                this.RaisePropertyChanged("TdrYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public double assetValue {
            get {
                return this.assetValueField;
            }
            set {
                this.assetValueField = value;
                this.RaisePropertyChanged("assetValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public double debtValue {
            get {
                return this.debtValueField;
            }
            set {
                this.debtValueField = value;
                this.RaisePropertyChanged("debtValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public double income {
            get {
                return this.incomeField;
            }
            set {
                this.incomeField = value;
                this.RaisePropertyChanged("income");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public double expense {
            get {
                return this.expenseField;
            }
            set {
                this.expenseField = value;
                this.RaisePropertyChanged("expense");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public double installmentAmount {
            get {
                return this.installmentAmountField;
            }
            set {
                this.installmentAmountField = value;
                this.RaisePropertyChanged("installmentAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public IsGetProfit isGetProfit {
            get {
                return this.isGetProfitField;
            }
            set {
                this.isGetProfitField = value;
                this.RaisePropertyChanged("isGetProfit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public int objectiveTerm {
            get {
                return this.objectiveTermField;
            }
            set {
                this.objectiveTermField = value;
                this.RaisePropertyChanged("objectiveTerm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public double loanAmount {
            get {
                return this.loanAmountField;
            }
            set {
                this.loanAmountField = value;
                this.RaisePropertyChanged("loanAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int yearInstallment {
            get {
                return this.yearInstallmentField;
            }
            set {
                this.yearInstallmentField = value;
                this.RaisePropertyChanged("yearInstallment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public int consent {
            get {
                return this.consentField;
            }
            set {
                this.consentField = value;
                this.RaisePropertyChanged("consent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string requestNo {
            get {
                return this.requestNoField;
            }
            set {
                this.requestNoField = value;
                this.RaisePropertyChanged("requestNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int eventType {
            get {
                return this.eventTypeField;
            }
            set {
                this.eventTypeField = value;
                this.RaisePropertyChanged("eventType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public double CostSale {
            get {
                return this.costSaleField;
            }
            set {
                this.costSaleField = value;
                this.RaisePropertyChanged("CostSale");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string LoanType {
            get {
                return this.loanTypeField;
            }
            set {
                this.loanTypeField = value;
                this.RaisePropertyChanged("LoanType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public double DSCR {
            get {
                return this.dSCRField;
            }
            set {
                this.dSCRField = value;
                this.RaisePropertyChanged("DSCR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public double LoanLCTR {
            get {
                return this.loanLCTRField;
            }
            set {
                this.loanLCTRField = value;
                this.RaisePropertyChanged("LoanLCTR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public double LoanLG {
            get {
                return this.loanLGField;
            }
            set {
                this.loanLGField = value;
                this.RaisePropertyChanged("LoanLG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public double LoanPN {
            get {
                return this.loanPNField;
            }
            set {
                this.loanPNField = value;
                this.RaisePropertyChanged("LoanPN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public double LoanOD {
            get {
                return this.loanODField;
            }
            set {
                this.loanODField = value;
                this.RaisePropertyChanged("LoanOD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public double LoanTL {
            get {
                return this.loanTLField;
            }
            set {
                this.loanTLField = value;
                this.RaisePropertyChanged("LoanTL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public double LoanOther {
            get {
                return this.loanOtherField;
            }
            set {
                this.loanOtherField = value;
                this.RaisePropertyChanged("LoanOther");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public double LandAsset {
            get {
                return this.landAssetField;
            }
            set {
                this.landAssetField = value;
                this.RaisePropertyChanged("LandAsset");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public double TCGScoreRBP {
            get {
                return this.tCGScoreRBPField;
            }
            set {
                this.tCGScoreRBPField = value;
                this.RaisePropertyChanged("TCGScoreRBP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public int TCGScoreTotalScore {
            get {
                return this.tCGScoreTotalScoreField;
            }
            set {
                this.tCGScoreTotalScoreField = value;
                this.RaisePropertyChanged("TCGScoreTotalScore");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string TCGScoreBand {
            get {
                return this.tCGScoreBandField;
            }
            set {
                this.tCGScoreBandField = value;
                this.RaisePropertyChanged("TCGScoreBand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public int TCGScoreBandLevel {
            get {
                return this.tCGScoreBandLevelField;
            }
            set {
                this.tCGScoreBandLevelField = value;
                this.RaisePropertyChanged("TCGScoreBandLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public System.Nullable<int> IsPassCreditBureau {
            get {
                return this.isPassCreditBureauField;
            }
            set {
                this.isPassCreditBureauField = value;
                this.RaisePropertyChanged("IsPassCreditBureau");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public System.Nullable<int> CreditBureauLevel {
            get {
                return this.creditBureauLevelField;
            }
            set {
                this.creditBureauLevelField = value;
                this.RaisePropertyChanged("CreditBureauLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string businessName {
            get {
                return this.businessNameField;
            }
            set {
                this.businessNameField = value;
                this.RaisePropertyChanged("businessName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string idCard {
            get {
                return this.idCardField;
            }
            set {
                this.idCardField = value;
                this.RaisePropertyChanged("idCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public bool IsPassProductCriteria {
            get {
                return this.isPassProductCriteriaField;
            }
            set {
                this.isPassProductCriteriaField = value;
                this.RaisePropertyChanged("IsPassProductCriteria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public double SumAsset {
            get {
                return this.sumAssetField;
            }
            set {
                this.sumAssetField = value;
                this.RaisePropertyChanged("SumAsset");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum PersonType {
        
        /// <remarks/>
        Person,
        
        /// <remarks/>
        Corporate,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum EstablishmentType {
        
        /// <remarks/>
        OfficeOwner,
        
        /// <remarks/>
        OfficeRental,
        
        /// <remarks/>
        NoShow,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum MaritalType {
        
        /// <remarks/>
        NoShow,
        
        /// <remarks/>
        Single,
        
        /// <remarks/>
        Married,
        
        /// <remarks/>
        Divorce,
        
        /// <remarks/>
        Widow,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DebtStatusType {
        
        /// <remarks/>
        NoDebt,
        
        /// <remarks/>
        OverdueLessThan90,
        
        /// <remarks/>
        OverdueMoreThan90,
        
        /// <remarks/>
        TDR,
        
        /// <remarks/>
        LegalProcess,
        
        /// <remarks/>
        InstallmentNormal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum IsGetProfit {
        
        /// <remarks/>
        Yes,
        
        /// <remarks/>
        No,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaskOfResultAPIInfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Task : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TaskOfResultAPIInfo : Task {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EmailInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string emailField;
        
        private string subjectField;
        
        private string bodyField;
        
        private string cCEmailField;
        
        private string senderField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CCEmail {
            get {
                return this.cCEmailField;
            }
            set {
                this.cCEmailField = value;
                this.RaisePropertyChanged("CCEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
                this.RaisePropertyChanged("Sender");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ScoreInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int scoreField;
        
        private int scoreGroupField;
        
        private string groupDescField;
        
        private string groupShortDescField;
        
        private string imageBGField;
        
        private string imageScoreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int score {
            get {
                return this.scoreField;
            }
            set {
                this.scoreField = value;
                this.RaisePropertyChanged("score");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int scoreGroup {
            get {
                return this.scoreGroupField;
            }
            set {
                this.scoreGroupField = value;
                this.RaisePropertyChanged("scoreGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string groupDesc {
            get {
                return this.groupDescField;
            }
            set {
                this.groupDescField = value;
                this.RaisePropertyChanged("groupDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string groupShortDesc {
            get {
                return this.groupShortDescField;
            }
            set {
                this.groupShortDescField = value;
                this.RaisePropertyChanged("groupShortDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ImageBG {
            get {
                return this.imageBGField;
            }
            set {
                this.imageBGField = value;
                this.RaisePropertyChanged("ImageBG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ImageScore {
            get {
                return this.imageScoreField;
            }
            set {
                this.imageScoreField = value;
                this.RaisePropertyChanged("ImageScore");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UIDMapCustomerProfileModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long codeField;
        
        private int idCardTypeField;
        
        private string idCardField;
        
        private string titleNameField;
        
        private string titleCodeField;
        
        private string nameField;
        
        private string sureNameField;
        
        private string companyNameField;
        
        private System.DateTime createDateTimeField;
        
        private bool isActiveField;
        
        private string idField;
        
        private string createByField;
        
        private string uidField;
        
        private string lineNameField;
        
        private string pictureField;
        
        private string uid_ChannelField;
        
        private string emailField;
        
        private string emailAddressField;
        
        private string mobileNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int IdCardType {
            get {
                return this.idCardTypeField;
            }
            set {
                this.idCardTypeField = value;
                this.RaisePropertyChanged("IdCardType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IdCard {
            get {
                return this.idCardField;
            }
            set {
                this.idCardField = value;
                this.RaisePropertyChanged("IdCard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string TitleName {
            get {
                return this.titleNameField;
            }
            set {
                this.titleNameField = value;
                this.RaisePropertyChanged("TitleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TitleCode {
            get {
                return this.titleCodeField;
            }
            set {
                this.titleCodeField = value;
                this.RaisePropertyChanged("TitleCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SureName {
            get {
                return this.sureNameField;
            }
            set {
                this.sureNameField = value;
                this.RaisePropertyChanged("SureName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime CreateDateTime {
            get {
                return this.createDateTimeField;
            }
            set {
                this.createDateTimeField = value;
                this.RaisePropertyChanged("CreateDateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string CreateBy {
            get {
                return this.createByField;
            }
            set {
                this.createByField = value;
                this.RaisePropertyChanged("CreateBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Uid {
            get {
                return this.uidField;
            }
            set {
                this.uidField = value;
                this.RaisePropertyChanged("Uid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string lineName {
            get {
                return this.lineNameField;
            }
            set {
                this.lineNameField = value;
                this.RaisePropertyChanged("lineName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
                this.RaisePropertyChanged("Picture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Uid_Channel {
            get {
                return this.uid_ChannelField;
            }
            set {
                this.uid_ChannelField = value;
                this.RaisePropertyChanged("Uid_Channel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string EmailAddress {
            get {
                return this.emailAddressField;
            }
            set {
                this.emailAddressField = value;
                this.RaisePropertyChanged("EmailAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string MobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("MobileNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RegisterControllerSoapChannel : CustomerHealthCheck.RegisterControllerService.RegisterControllerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RegisterControllerSoapClient : System.ServiceModel.ClientBase<CustomerHealthCheck.RegisterControllerService.RegisterControllerSoap>, CustomerHealthCheck.RegisterControllerService.RegisterControllerSoap {
        
        public RegisterControllerSoapClient() {
        }
        
        public RegisterControllerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RegisterControllerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterControllerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RegisterControllerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CustomerHealthCheck.RegisterControllerService.RegisterInfo newRegisterInfo() {
            return base.Channel.newRegisterInfo();
        }
        
        public System.Data.DataTable GetProvince() {
            return base.Channel.GetProvince();
        }
        
        public System.Data.DataTable GetIndustryType() {
            return base.Channel.GetIndustryType();
        }
        
        public System.Data.DataTable GetTitleName(CustomerHealthCheck.RegisterControllerService.PersonType type) {
            return base.Channel.GetTitleName(type);
        }
        
        public System.Data.DataTable GetObjTerm() {
            return base.Channel.GetObjTerm();
        }
        
        public System.Data.DataTable GetChannel() {
            return base.Channel.GetChannel();
        }
        
        public CustomerHealthCheck.RegisterControllerService.UIDMapCustomerProfileModel GetUIDMapRegiterType(string uid, string type) {
            return base.Channel.GetUIDMapRegiterType(uid, type);
        }
        
        public CustomerHealthCheck.RegisterControllerService.ScoreInfo calculateScore(CustomerHealthCheck.RegisterControllerService.RegisterInfo info) {
            return base.Channel.calculateScore(info);
        }
        
        public CustomerHealthCheck.RegisterControllerService.RegisterInfo calculateDSCR(CustomerHealthCheck.RegisterControllerService.RegisterInfo info) {
            return base.Channel.calculateDSCR(info);
        }
        
        public CustomerHealthCheck.RegisterControllerService.RegisterInfo calculateTCGScoreAndRBP(CustomerHealthCheck.RegisterControllerService.RegisterInfo info) {
            return base.Channel.calculateTCGScoreAndRBP(info);
        }
        
        public int InsertRegisterInfo(CustomerHealthCheck.RegisterControllerService.RegisterInfo info, CustomerHealthCheck.RegisterControllerService.ScoreInfo score) {
            return base.Channel.InsertRegisterInfo(info, score);
        }
        
        public string InsertCustomerProfile(CustomerHealthCheck.RegisterControllerService.RegisterInfo info) {
            return base.Channel.InsertCustomerProfile(info);
        }
        
        public void InsertContactProfile(CustomerHealthCheck.RegisterControllerService.RegisterInfo info, string customerCode, string email) {
            base.Channel.InsertContactProfile(info, customerCode, email);
        }
        
        public string InsertRequest(string customerCode) {
            return base.Channel.InsertRequest(customerCode);
        }
        
        public void InsertFieldData(CustomerHealthCheck.RegisterControllerService.RegisterInfo info, CustomerHealthCheck.RegisterControllerService.ScoreInfo score) {
            base.Channel.InsertFieldData(info, score);
        }
        
        public bool InsertUIDRegisterInfo(string uid, int registerInfoId, string infoType, string subInfoType) {
            return base.Channel.InsertUIDRegisterInfo(uid, registerInfoId, infoType, subInfoType);
        }
        
        public bool UpdateRegisterInfo(CustomerHealthCheck.RegisterControllerService.RegisterInfo info) {
            return base.Channel.UpdateRegisterInfo(info);
        }
        
        public bool UpdateConsent(CustomerHealthCheck.RegisterControllerService.RegisterInfo info) {
            return base.Channel.UpdateConsent(info);
        }
        
        public bool UpdateCodeFromClinic(int id, string clinicCustomerCode, string clinicRequestNo) {
            return base.Channel.UpdateCodeFromClinic(id, clinicCustomerCode, clinicRequestNo);
        }
        
        public bool UpdateUID(string uid, string customerProfileCode) {
            return base.Channel.UpdateUID(uid, customerProfileCode);
        }
        
        public CustomerHealthCheck.RegisterControllerService.TaskOfResultAPIInfo SendEmail(CustomerHealthCheck.RegisterControllerService.EmailInfo emailInfo) {
            return base.Channel.SendEmail(emailInfo);
        }
    }
}
